name: dev-env

on:
  push:
    tags:
      - "v1.*"

jobs:
  build:
    #if: ${{ !contains(github.event.head_commit.message, '#build') }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'dev') == false
        run: exit -1

      - uses: actions/checkout@v3
      - name: branch checking
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
      - run: npm run build
      - run: echo "this is running in group runner"
