name: dev-env

on:
  push:
    branches: ["dev"]
    tags:
      - "v1.*"

jobs:
  build:
    ##if: ${{ !contains(github.event.head_commit.message, '#build') }}
    runs-on: self-hosted

    steps:
      - name: branch checking
        uses: actions/setup-node@v3

      #- run: npm i
      #- run: npm run build
      - run: echo "this is running in group runner"
